before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/pru
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
checksum:
  name_template: "checksums.txt"
brews:
  - tap:
      owner: winebarrel
      name: homebrew-pru
    homepage: https://github.com/winebarrel/pru
    description: pru is a tool that updates pull requests branch from the base branch that contains specified files.
    license: MIT
    install: |
      bin.install 'pru'
nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/winebarrel/pru
    maintainer: Genki Sugawara <sugawara@winebarrel.jp>
    description: pru is a tool that updates pull requests branch from the base branch that contains specified files.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
